    public class PeriodicView : Gtk.Grid {

        HeaderBar headerBar = HeaderBar.get_instance();

        static PeriodicView? instance;

        public static PeriodicView get_instance() {
            if (instance == null) {
                instance = new PeriodicView(elements.MAIN_VIEW_ID);
            }
            return instance;
        }

        public PeriodicView(string id) {
            headerBar.showPeriodicViewMode(true);

            this.row_spacing = 3;
            this.column_spacing = 3;
            this.row_homogeneous = true;
            this.column_homogeneous = true;

            var b001 = new Gtk.Label(H.ID);
            var b002 = new Gtk.Label(He.ID);
            var b003 = new Gtk.Label(Li.ID);
            var b004 = new Gtk.Label(Be.ID);
            var b005 = new Gtk.Label(B.ID);
            var b006 = new Gtk.Label(C.ID);
            var b007 = new Gtk.Label(N.ID);
            var b008 = new Gtk.Label(O.ID);
            var b009 = new Gtk.Label(F.ID);
            var b010 = new Gtk.Label(Ne.ID);
            var b011 = new Gtk.Label(Na.ID);
            var b012 = new Gtk.Label(Mg.ID);
            var b013 = new Gtk.Label(Al.ID);
            var b014 = new Gtk.Label(Si.ID);
            var b015 = new Gtk.Label(P.ID);
            var b016 = new Gtk.Label(S.ID);
            var b017 = new Gtk.Label(Cl.ID);
            var b018 = new Gtk.Label(Ar.ID);
            var b019 = new Gtk.Label(K.ID);
            var b020 = new Gtk.Label(Ca.ID);
            var b021 = new Gtk.Label(Sc.ID);
            var b022 = new Gtk.Label(Ti.ID);
            var b023 = new Gtk.Label(V.ID);
            var b024 = new Gtk.Label(Cr.ID);
            var b025 = new Gtk.Label(Mn.ID);
            var b026 = new Gtk.Label(Fe.ID);
            var b027 = new Gtk.Label(Co.ID);
            var b028 = new Gtk.Label(Ni.ID);
            var b029 = new Gtk.Label(Cu.ID);
            var b030 = new Gtk.Label(Zn.ID);
            var b031 = new Gtk.Label(Ga.ID);
            var b032 = new Gtk.Label(Ge.ID);
            var b033 = new Gtk.Label(As.ID);
            var b034 = new Gtk.Label(Se.ID);
            var b035 = new Gtk.Label(Br.ID);
            var b036 = new Gtk.Label(Kr.ID);
            var b037 = new Gtk.Label(Rb.ID);
            var b038 = new Gtk.Label(Sr.ID);
            var b039 = new Gtk.Label(Y.ID);
            var b040 = new Gtk.Label(Zr.ID);
            var b041 = new Gtk.Label(Nb.ID);
            var b042 = new Gtk.Label(Mo.ID);
            var b043 = new Gtk.Label(Tc.ID);
            var b044 = new Gtk.Label(Ru.ID);
            var b045 = new Gtk.Label(Rh.ID);
            var b046 = new Gtk.Label(Pd.ID);
            var b047 = new Gtk.Label(Ag.ID);
            var b048 = new Gtk.Label(Cd.ID);
            var b049 = new Gtk.Label(In.ID);
            var b050 = new Gtk.Label(Sn.ID);
            var b051 = new Gtk.Label(Sb.ID);
            var b052 = new Gtk.Label(Te.ID);
            var b053 = new Gtk.Label(I.ID);
            var b054 = new Gtk.Label(Xe.ID);
            var b055 = new Gtk.Label(Cs.ID);
            var b056 = new Gtk.Label(Ba.ID);
            var b057 = new Gtk.Label(La.ID);
            var b058 = new Gtk.Label(Ce.ID);
            var b059 = new Gtk.Label(Pr.ID);
            var b060 = new Gtk.Label(Nd.ID);
            var b061 = new Gtk.Label(Pm.ID);
            var b062 = new Gtk.Label(Sm.ID);
            var b063 = new Gtk.Label(Eu.ID);
            var b064 = new Gtk.Label(Gd.ID);
            var b065 = new Gtk.Label(Tb.ID);
            var b066 = new Gtk.Label(Dy.ID);
            var b067 = new Gtk.Label(Ho.ID);
            var b068 = new Gtk.Label(Er.ID);
            var b069 = new Gtk.Label(Tm.ID);
            var b070 = new Gtk.Label(Yb.ID);
            var b071 = new Gtk.Label(Lu.ID);
            var b072 = new Gtk.Label(Hf.ID);
            var b073 = new Gtk.Label(Ta.ID);
            var b074 = new Gtk.Label(W.ID);
            var b075 = new Gtk.Label(Re.ID);
            var b076 = new Gtk.Label(Os.ID);
            var b077 = new Gtk.Label(Ir.ID);
            var b078 = new Gtk.Label(Pt.ID);
            var b079 = new Gtk.Label(Au.ID);
            var b080 = new Gtk.Label(Hg.ID);
            var b081 = new Gtk.Label(Tl.ID);
            var b082 = new Gtk.Label(Pb.ID);
            var b083 = new Gtk.Label(Bi.ID);
            var b084 = new Gtk.Label(Po.ID);
            var b085 = new Gtk.Label(At.ID);
            var b086 = new Gtk.Label(Rn.ID);
            var b087 = new Gtk.Label(Fr.ID);
            var b088 = new Gtk.Label(Ra.ID);
            var b089 = new Gtk.Label(Ac.ID);
            var b090 = new Gtk.Label(Th.ID);
            var b091 = new Gtk.Label(Pa.ID);
            var b092 = new Gtk.Label(U.ID);
            var b093 = new Gtk.Label(Np.ID);
            var b094 = new Gtk.Label(Pu.ID);
            var b095 = new Gtk.Label(Am.ID);
            var b096 = new Gtk.Label(Cm.ID);
            var b097 = new Gtk.Label(Bk.ID);
            var b098 = new Gtk.Label(Cf.ID);
            var b099 = new Gtk.Label(Es.ID);
            var b100 = new Gtk.Label(Fm.ID);
            var b101 = new Gtk.Label(Md.ID);
            var b102 = new Gtk.Label(No.ID);
            var b103 = new Gtk.Label(Lr.ID);
            var b104 = new Gtk.Label(Rf.ID);
            var b105 = new Gtk.Label(Db.ID);
            var b106 = new Gtk.Label(Sg.ID);
            var b107 = new Gtk.Label(Bh.ID);
            var b108 = new Gtk.Label(Hs.ID);
            var b109 = new Gtk.Label(Mt.ID);
            var b110 = new Gtk.Label(Ds.ID);
            var b111 = new Gtk.Label(Rg.ID);
            var b112 = new Gtk.Label(Cn.ID);
            var b113 = new Gtk.Label(Nh.ID);
            var b114 = new Gtk.Label(Fl.ID);
            var b115 = new Gtk.Label(Mc.ID);
            var b116 = new Gtk.Label(Lv.ID);
            var b117 = new Gtk.Label(Ts.ID);
            var b118 = new Gtk.Label(Og.ID);

            var x = new Gtk.Label("*");
            var xx = new Gtk.Label("**");

            this.attach(new Gtk.Label(" "), 0, 8);
            this.attach(x, 2, 6);
            this.attach(xx, 2, 7);

            this.attach(b001, 0, 1);
            this.attach(b002, 17, 1);
            this.attach(b003, 0, 2);
            this.attach(b004, 1, 2);
            this.attach(b005, 12, 2);
            this.attach(b006, 13, 2);
            this.attach(b007, 14, 2);
            this.attach(b008, 15, 2);
            this.attach(b009, 16, 2);
            this.attach(b010, 17, 2);
            this.attach(b011, 0, 3);
            this.attach(b012, 1, 3);
            this.attach(b013, 12, 3);
            this.attach(b014, 13, 3);
            this.attach(b015, 14, 3);
            this.attach(b016, 15, 3);
            this.attach(b017, 16, 3);
            this.attach(b018, 17, 3);
            this.attach(b019, 0, 4);
            this.attach(b020, 1, 4);
            this.attach(b021, 2, 4);
            this.attach(b022, 3, 4);
            this.attach(b023, 4, 4);
            this.attach(b024, 5, 4);
            this.attach(b025, 6, 4);
            this.attach(b026, 7, 4);
            this.attach(b027, 8, 4);
            this.attach(b028, 9, 4);
            this.attach(b029, 10, 4);
            this.attach(b030, 11, 4);
            this.attach(b031, 12, 4);
            this.attach(b032, 13, 4);
            this.attach(b033, 14, 4);
            this.attach(b034, 15, 4);
            this.attach(b035, 16, 4);
            this.attach(b036, 17, 4);
            this.attach(b037, 0, 5);
            this.attach(b038, 1, 5);
            this.attach(b039, 2, 5);
            this.attach(b040, 3, 5);
            this.attach(b041, 4, 5);
            this.attach(b042, 5, 5);
            this.attach(b043, 6, 5);
            this.attach(b044, 7, 5);
            this.attach(b045, 8, 5);
            this.attach(b046, 9, 5);
            this.attach(b047, 10, 5);
            this.attach(b048, 11, 5);
            this.attach(b049, 12, 5);
            this.attach(b050, 13, 5);
            this.attach(b051, 14, 5);
            this.attach(b052, 15, 5);
            this.attach(b053, 16, 5);
            this.attach(b054, 17, 5);
            this.attach(b055, 0, 6);
            this.attach(b056, 1, 6);
            this.attach(b057, 2, 10);
            this.attach(b058, 3, 10);
            this.attach(b059, 4, 10);
            this.attach(b060, 5, 10);
            this.attach(b061, 6, 10);
            this.attach(b062, 7, 10);
            this.attach(b063, 8, 10);
            this.attach(b064, 9, 10);
            this.attach(b065, 10, 10);
            this.attach(b066, 11, 10);
            this.attach(b067, 12, 10);
            this.attach(b068, 13, 10);
            this.attach(b069, 14, 10);
            this.attach(b070, 15, 10);
            this.attach(b071, 16, 10);
            this.attach(b072, 3, 6);
            this.attach(b073, 4, 6);
            this.attach(b074, 5, 6);
            this.attach(b075, 6, 6);
            this.attach(b076, 7, 6);
            this.attach(b077, 8, 6);
            this.attach(b078, 9, 6);
            this.attach(b079, 10, 6);
            this.attach(b080, 11, 6);
            this.attach(b081, 12, 6);
            this.attach(b082, 13, 6);
            this.attach(b083, 14, 6);
            this.attach(b084, 15, 6);
            this.attach(b085, 16, 6);
            this.attach(b086, 17, 6);
            this.attach(b087, 0, 7);
            this.attach(b088, 1, 7);
            this.attach(b089, 2, 11);
            this.attach(b090, 3, 11);
            this.attach(b091, 4, 11);
            this.attach(b092, 5, 11);
            this.attach(b093, 6, 11);
            this.attach(b094, 7, 11);
            this.attach(b095, 8, 11);
            this.attach(b096, 9, 11);
            this.attach(b097, 10, 11);
            this.attach(b098, 11, 11);
            this.attach(b099, 12, 11);
            this.attach(b100, 13, 11);
            this.attach(b101, 14, 11);
            this.attach(b102, 15, 11);
            this.attach(b103, 16, 11);
            this.attach(b104, 3, 7);
            this.attach(b105, 4, 7);
            this.attach(b106, 5, 7);
            this.attach(b107, 6, 7);
            this.attach(b108, 7, 7);
            this.attach(b109, 8, 7);
            this.attach(b110, 9, 7);
            this.attach(b111, 10, 7);
            this.attach(b112, 11, 7);
            this.attach(b113, 12, 7);
            this.attach(b114, 13, 7);
            this.attach(b115, 14, 7);
            this.attach(b116, 15, 7);
            this.attach(b117, 16, 7);
            this.attach(b118, 17, 7);

            if(id == elements.MAIN_VIEW_ID) {
                x.get_style_context().add_class(elements.LANTHANIDE);
                xx.get_style_context().add_class(elements.ACTINIDE);

                b001.get_style_context().add_class(elements.OTHER_NONMETAL);
                b006.get_style_context().add_class(elements.OTHER_NONMETAL);
                b007.get_style_context().add_class(elements.OTHER_NONMETAL);
                b008.get_style_context().add_class(elements.OTHER_NONMETAL);
                b015.get_style_context().add_class(elements.OTHER_NONMETAL);
                b016.get_style_context().add_class(elements.OTHER_NONMETAL);
                b034.get_style_context().add_class(elements.OTHER_NONMETAL);
                b003.get_style_context().add_class(elements.ALKALI_METAL);
                b011.get_style_context().add_class(elements.ALKALI_METAL);
                b019.get_style_context().add_class(elements.ALKALI_METAL);
                b037.get_style_context().add_class(elements.ALKALI_METAL);
                b055.get_style_context().add_class(elements.ALKALI_METAL);
                b087.get_style_context().add_class(elements.ALKALI_METAL);
                b004.get_style_context().add_class(elements.ALKALINE_EARTH_METAL);
                b012.get_style_context().add_class(elements.ALKALINE_EARTH_METAL);
                b020.get_style_context().add_class(elements.ALKALINE_EARTH_METAL);
                b038.get_style_context().add_class(elements.ALKALINE_EARTH_METAL);
                b056.get_style_context().add_class(elements.ALKALINE_EARTH_METAL);
                b088.get_style_context().add_class(elements.ALKALINE_EARTH_METAL);
                b021.get_style_context().add_class(elements.TRANSITION_METAL);
                b022.get_style_context().add_class(elements.TRANSITION_METAL);
                b023.get_style_context().add_class(elements.TRANSITION_METAL);
                b024.get_style_context().add_class(elements.TRANSITION_METAL);
                b025.get_style_context().add_class(elements.TRANSITION_METAL);
                b026.get_style_context().add_class(elements.TRANSITION_METAL);
                b027.get_style_context().add_class(elements.TRANSITION_METAL);
                b028.get_style_context().add_class(elements.TRANSITION_METAL);
                b029.get_style_context().add_class(elements.TRANSITION_METAL);
                b030.get_style_context().add_class(elements.TRANSITION_METAL);
                b039.get_style_context().add_class(elements.TRANSITION_METAL);
                b040.get_style_context().add_class(elements.TRANSITION_METAL);
                b041.get_style_context().add_class(elements.TRANSITION_METAL);
                b042.get_style_context().add_class(elements.TRANSITION_METAL);
                b043.get_style_context().add_class(elements.TRANSITION_METAL);
                b044.get_style_context().add_class(elements.TRANSITION_METAL);
                b045.get_style_context().add_class(elements.TRANSITION_METAL);
                b046.get_style_context().add_class(elements.TRANSITION_METAL);
                b047.get_style_context().add_class(elements.TRANSITION_METAL);
                b048.get_style_context().add_class(elements.TRANSITION_METAL);
                b072.get_style_context().add_class(elements.TRANSITION_METAL);
                b073.get_style_context().add_class(elements.TRANSITION_METAL);
                b074.get_style_context().add_class(elements.TRANSITION_METAL);
                b075.get_style_context().add_class(elements.TRANSITION_METAL);
                b076.get_style_context().add_class(elements.TRANSITION_METAL);
                b077.get_style_context().add_class(elements.TRANSITION_METAL);
                b078.get_style_context().add_class(elements.TRANSITION_METAL);
                b079.get_style_context().add_class(elements.TRANSITION_METAL);
                b080.get_style_context().add_class(elements.TRANSITION_METAL);
                b104.get_style_context().add_class(elements.TRANSITION_METAL);
                b105.get_style_context().add_class(elements.TRANSITION_METAL);
                b106.get_style_context().add_class(elements.TRANSITION_METAL);
                b107.get_style_context().add_class(elements.TRANSITION_METAL);
                b108.get_style_context().add_class(elements.TRANSITION_METAL);
                b109.get_style_context().add_class(elements.TRANSITION_METAL);
                b110.get_style_context().add_class(elements.TRANSITION_METAL);
                b111.get_style_context().add_class(elements.TRANSITION_METAL);
                b112.get_style_context().add_class(elements.TRANSITION_METAL);
                b013.get_style_context().add_class(elements.POST_TRANSITION_METAL);
                b031.get_style_context().add_class(elements.POST_TRANSITION_METAL);
                b049.get_style_context().add_class(elements.POST_TRANSITION_METAL);
                b050.get_style_context().add_class(elements.POST_TRANSITION_METAL);
                b081.get_style_context().add_class(elements.POST_TRANSITION_METAL);
                b082.get_style_context().add_class(elements.POST_TRANSITION_METAL);
                b083.get_style_context().add_class(elements.POST_TRANSITION_METAL);
                b113.get_style_context().add_class(elements.POST_TRANSITION_METAL);
                b115.get_style_context().add_class(elements.POST_TRANSITION_METAL);
                b114.get_style_context().add_class(elements.POST_TRANSITION_METAL);
                b116.get_style_context().add_class(elements.POST_TRANSITION_METAL);
                b005.get_style_context().add_class(elements.METALLOID);
                b014.get_style_context().add_class(elements.METALLOID);
                b032.get_style_context().add_class(elements.METALLOID);
                b033.get_style_context().add_class(elements.METALLOID);
                b051.get_style_context().add_class(elements.METALLOID);
                b052.get_style_context().add_class(elements.METALLOID);
                b084.get_style_context().add_class(elements.METALLOID);
                b009.get_style_context().add_class(elements.HALOGEN);
                b017.get_style_context().add_class(elements.HALOGEN);
                b035.get_style_context().add_class(elements.HALOGEN);
                b053.get_style_context().add_class(elements.HALOGEN);
                b085.get_style_context().add_class(elements.HALOGEN);
                b117.get_style_context().add_class(elements.HALOGEN);
                b002.get_style_context().add_class(elements.NOBLE_GAS);
                b010.get_style_context().add_class(elements.NOBLE_GAS);
                b018.get_style_context().add_class(elements.NOBLE_GAS);
                b036.get_style_context().add_class(elements.NOBLE_GAS);
                b054.get_style_context().add_class(elements.NOBLE_GAS);
                b086.get_style_context().add_class(elements.NOBLE_GAS);
                b118.get_style_context().add_class(elements.NOBLE_GAS);
                b057.get_style_context().add_class(elements.LANTHANIDE);
                b058.get_style_context().add_class(elements.LANTHANIDE);
                b059.get_style_context().add_class(elements.LANTHANIDE);
                b060.get_style_context().add_class(elements.LANTHANIDE);
                b061.get_style_context().add_class(elements.LANTHANIDE);
                b062.get_style_context().add_class(elements.LANTHANIDE);
                b063.get_style_context().add_class(elements.LANTHANIDE);
                b064.get_style_context().add_class(elements.LANTHANIDE);
                b065.get_style_context().add_class(elements.LANTHANIDE);
                b066.get_style_context().add_class(elements.LANTHANIDE);
                b067.get_style_context().add_class(elements.LANTHANIDE);
                b068.get_style_context().add_class(elements.LANTHANIDE);
                b069.get_style_context().add_class(elements.LANTHANIDE);
                b070.get_style_context().add_class(elements.LANTHANIDE);
                b071.get_style_context().add_class(elements.LANTHANIDE);
                b089.get_style_context().add_class(elements.ACTINIDE);
                b090.get_style_context().add_class(elements.ACTINIDE);
                b091.get_style_context().add_class(elements.ACTINIDE);
                b092.get_style_context().add_class(elements.ACTINIDE);
                b093.get_style_context().add_class(elements.ACTINIDE);
                b094.get_style_context().add_class(elements.ACTINIDE);
                b095.get_style_context().add_class(elements.ACTINIDE);
                b096.get_style_context().add_class(elements.ACTINIDE);
                b097.get_style_context().add_class(elements.ACTINIDE);
                b098.get_style_context().add_class(elements.ACTINIDE);
                b099.get_style_context().add_class(elements.ACTINIDE);
                b100.get_style_context().add_class(elements.ACTINIDE);
                b101.get_style_context().add_class(elements.ACTINIDE);
                b102.get_style_context().add_class(elements.ACTINIDE);
                b103.get_style_context().add_class(elements.ACTINIDE);
            } if(id == elements.ELECTRO_VIEW_ID) {
                x.get_style_context().add_class(elements.ZEROeV);
                xx.get_style_context().add_class(elements.ZEROeV);

                b002.get_style_context().add_class(elements.ZEROeV);
                b010.get_style_context().add_class(elements.ZEROeV);
                b018.get_style_context().add_class(elements.ZEROeV);
                b036.get_style_context().add_class(elements.FOUReV);
                b054.get_style_context().add_class(elements.THREEeV);
                b057.get_style_context().add_class(elements.ONEeV);
                b058.get_style_context().add_class(elements.ONEeV);
                b059.get_style_context().add_class(elements.ONEeV);
                b060.get_style_context().add_class(elements.ONEeV);
                b061.get_style_context().add_class(elements.ONEeV);
                b062.get_style_context().add_class(elements.ONEeV);
                b063.get_style_context().add_class(elements.ONEeV);
                b064.get_style_context().add_class(elements.ONEeV);
                b065.get_style_context().add_class(elements.ONEeV);
                b066.get_style_context().add_class(elements.ONEeV);
                b067.get_style_context().add_class(elements.ONEeV);
                b068.get_style_context().add_class(elements.ONEeV);
                b069.get_style_context().add_class(elements.ONEeV);
                b070.get_style_context().add_class(elements.ONEeV);
                b071.get_style_context().add_class(elements.ONEeV);
                b086.get_style_context().add_class(elements.THREEeV);
                b089.get_style_context().add_class(elements.ONEeV);
                b090.get_style_context().add_class(elements.ONEeV);
                b091.get_style_context().add_class(elements.ONEeV);
                b092.get_style_context().add_class(elements.TWOeV);
                b093.get_style_context().add_class(elements.TWOeV);
                b094.get_style_context().add_class(elements.TWOeV);
                b095.get_style_context().add_class(elements.ONEeV);
                b096.get_style_context().add_class(elements.ONEeV);
                b097.get_style_context().add_class(elements.ONEeV);
                b098.get_style_context().add_class(elements.ONEeV);
                b099.get_style_context().add_class(elements.ONEeV);
                b100.get_style_context().add_class(elements.ONEeV);
                b101.get_style_context().add_class(elements.ONEeV);
                b102.get_style_context().add_class(elements.ONEeV);
                b103.get_style_context().add_class(elements.ONEeV);
                b104.get_style_context().add_class(elements.ZEROeV);
                b105.get_style_context().add_class(elements.ZEROeV);
                b106.get_style_context().add_class(elements.ZEROeV);
                b107.get_style_context().add_class(elements.ZEROeV);
                b108.get_style_context().add_class(elements.ZEROeV);
                b109.get_style_context().add_class(elements.ZEROeV);
                b110.get_style_context().add_class(elements.ZEROeV);
                b111.get_style_context().add_class(elements.ZEROeV);
                b112.get_style_context().add_class(elements.ZEROeV);
                b113.get_style_context().add_class(elements.ZEROeV);
                b114.get_style_context().add_class(elements.ZEROeV);
                b115.get_style_context().add_class(elements.ZEROeV);
                b116.get_style_context().add_class(elements.ZEROeV);
                b117.get_style_context().add_class(elements.ZEROeV);
                b118.get_style_context().add_class(elements.ZEROeV);
                b003.get_style_context().add_class(elements.ONEeV);
                b011.get_style_context().add_class(elements.ONEeV);
                b012.get_style_context().add_class(elements.ONEeV);
                b019.get_style_context().add_class(elements.ONEeV);
                b020.get_style_context().add_class(elements.ONEeV);
                b037.get_style_context().add_class(elements.ONEeV);
                b038.get_style_context().add_class(elements.ONEeV);
                b039.get_style_context().add_class(elements.ONEeV);
                b055.get_style_context().add_class(elements.ONEeV);
                b056.get_style_context().add_class(elements.ONEeV);
                b087.get_style_context().add_class(elements.ONEeV);
                b088.get_style_context().add_class(elements.ONEeV);
                b004.get_style_context().add_class(elements.TWOeV);
                b013.get_style_context().add_class(elements.TWOeV);
                b014.get_style_context().add_class(elements.TWOeV);
                b021.get_style_context().add_class(elements.TWOeV);
                b022.get_style_context().add_class(elements.TWOeV);
                b023.get_style_context().add_class(elements.TWOeV);
                b024.get_style_context().add_class(elements.TWOeV);
                b025.get_style_context().add_class(elements.TWOeV);
                b026.get_style_context().add_class(elements.TWOeV);
                b028.get_style_context().add_class(elements.TWOeV);
                b030.get_style_context().add_class(elements.TWOeV);
                b031.get_style_context().add_class(elements.TWOeV);
                b032.get_style_context().add_class(elements.TWOeV);
                b040.get_style_context().add_class(elements.TWOeV);
                b041.get_style_context().add_class(elements.TWOeV);
                b042.get_style_context().add_class(elements.TWOeV);
                b048.get_style_context().add_class(elements.TWOeV);
                b049.get_style_context().add_class(elements.TWOeV);
                b050.get_style_context().add_class(elements.TWOeV);
                b072.get_style_context().add_class(elements.TWOeV);
                b073.get_style_context().add_class(elements.TWOeV);
                b074.get_style_context().add_class(elements.TWOeV);
                b081.get_style_context().add_class(elements.TWOeV);
                b001.get_style_context().add_class(elements.THREEeV);
                b005.get_style_context().add_class(elements.THREEeV);
                b015.get_style_context().add_class(elements.THREEeV);
                b027.get_style_context().add_class(elements.THREEeV);
                b029.get_style_context().add_class(elements.THREEeV);
                b033.get_style_context().add_class(elements.THREEeV);
                b043.get_style_context().add_class(elements.THREEeV);
                b044.get_style_context().add_class(elements.THREEeV);
                b045.get_style_context().add_class(elements.THREEeV);
                b046.get_style_context().add_class(elements.THREEeV);
                b047.get_style_context().add_class(elements.THREEeV);
                b051.get_style_context().add_class(elements.THREEeV);
                b052.get_style_context().add_class(elements.THREEeV);
                b075.get_style_context().add_class(elements.THREEeV);
                b076.get_style_context().add_class(elements.THREEeV);
                b077.get_style_context().add_class(elements.THREEeV);
                b078.get_style_context().add_class(elements.THREEeV);
                b080.get_style_context().add_class(elements.THREEeV);
                b082.get_style_context().add_class(elements.THREEeV);
                b083.get_style_context().add_class(elements.THREEeV);
                b084.get_style_context().add_class(elements.THREEeV);
                b085.get_style_context().add_class(elements.THREEeV);
                b006.get_style_context().add_class(elements.FOUReV);
                b016.get_style_context().add_class(elements.FOUReV);
                b034.get_style_context().add_class(elements.FOUReV);
                b035.get_style_context().add_class(elements.FOUReV);
                b053.get_style_context().add_class(elements.FOUReV);
                b079.get_style_context().add_class(elements.FOUReV);
                b007.get_style_context().add_class(elements.FIVEeV);
                b008.get_style_context().add_class(elements.FIVEeV);
                b017.get_style_context().add_class(elements.FIVEeV);
                b009.get_style_context().add_class(elements.SIXeV);
            }
/*
            b001.clicked.connect(on_click);
            b002.clicked.connect(on_click);
            b003.clicked.connect(on_click);
            b004.clicked.connect(on_click);
            b005.clicked.connect(on_click);
            b006.clicked.connect(on_click);
            b007.clicked.connect(on_click);
            b008.clicked.connect(on_click);
            b009.clicked.connect(on_click);
            b010.clicked.connect(on_click);
            b011.clicked.connect(on_click);
            b012.clicked.connect(on_click);
            b013.clicked.connect(on_click);
            b014.clicked.connect(on_click);
            b015.clicked.connect(on_click);
            b016.clicked.connect(on_click);
            b017.clicked.connect(on_click);
            b018.clicked.connect(on_click);
            b019.clicked.connect(on_click);
            b020.clicked.connect(on_click);
            b021.clicked.connect(on_click);
            b022.clicked.connect(on_click);
            b023.clicked.connect(on_click);
            b024.clicked.connect(on_click);
            b025.clicked.connect(on_click);
            b026.clicked.connect(on_click);
            b027.clicked.connect(on_click);
            b028.clicked.connect(on_click);
            b029.clicked.connect(on_click);
            b030.clicked.connect(on_click);
            b031.clicked.connect(on_click);
            b032.clicked.connect(on_click);
            b033.clicked.connect(on_click);
            b034.clicked.connect(on_click);
            b035.clicked.connect(on_click);
            b036.clicked.connect(on_click);
            b037.clicked.connect(on_click);
            b038.clicked.connect(on_click);
            b039.clicked.connect(on_click);
            b040.clicked.connect(on_click);
            b041.clicked.connect(on_click);
            b042.clicked.connect(on_click);
            b043.clicked.connect(on_click);
            b044.clicked.connect(on_click);
            b045.clicked.connect(on_click);
            b046.clicked.connect(on_click);
            b047.clicked.connect(on_click);
            b048.clicked.connect(on_click);
            b049.clicked.connect(on_click);
            b050.clicked.connect(on_click);
            b051.clicked.connect(on_click);
            b052.clicked.connect(on_click);
            b053.clicked.connect(on_click);
            b054.clicked.connect(on_click);
            b055.clicked.connect(on_click);
            b056.clicked.connect(on_click);
            b057.clicked.connect(on_click);
            b058.clicked.connect(on_click);
            b059.clicked.connect(on_click);
            b060.clicked.connect(on_click);
            b061.clicked.connect(on_click);
            b062.clicked.connect(on_click);
            b063.clicked.connect(on_click);
            b064.clicked.connect(on_click);
            b065.clicked.connect(on_click);
            b066.clicked.connect(on_click);
            b067.clicked.connect(on_click);
            b068.clicked.connect(on_click);
            b069.clicked.connect(on_click);
            b070.clicked.connect(on_click);
            b071.clicked.connect(on_click);
            b072.clicked.connect(on_click);
            b073.clicked.connect(on_click);
            b074.clicked.connect(on_click);
            b075.clicked.connect(on_click);
            b076.clicked.connect(on_click);
            b077.clicked.connect(on_click);
            b078.clicked.connect(on_click);
            b079.clicked.connect(on_click);
            b080.clicked.connect(on_click);
            b081.clicked.connect(on_click);
            b082.clicked.connect(on_click);
            b083.clicked.connect(on_click);
            b084.clicked.connect(on_click);
            b085.clicked.connect(on_click);
            b086.clicked.connect(on_click);
            b087.clicked.connect(on_click);
            b088.clicked.connect(on_click);
            b089.clicked.connect(on_click);
            b090.clicked.connect(on_click);
            b091.clicked.connect(on_click);
            b092.clicked.connect(on_click);
            b093.clicked.connect(on_click);
            b094.clicked.connect(on_click);
            b095.clicked.connect(on_click);
            b096.clicked.connect(on_click);
            b097.clicked.connect(on_click);
            b098.clicked.connect(on_click);
            b099.clicked.connect(on_click);
            b100.clicked.connect(on_click);
            b101.clicked.connect(on_click);
            b102.clicked.connect(on_click);
            b103.clicked.connect(on_click);
            b104.clicked.connect(on_click);
            b105.clicked.connect(on_click);
            b106.clicked.connect(on_click);
            b107.clicked.connect(on_click);
            b108.clicked.connect(on_click);
            b109.clicked.connect(on_click);
            b110.clicked.connect(on_click);
            b111.clicked.connect(on_click);
            b112.clicked.connect(on_click);
            b113.clicked.connect(on_click);
            b114.clicked.connect(on_click);
            b115.clicked.connect(on_click);
            b116.clicked.connect(on_click);
            b117.clicked.connect(on_click);
            b118.clicked.connect(on_click);
        }

        public void on_click(Gtk.Button btn) {
//            var label = btn.label.to_string();

            headerBar.custom_title = headerBar.atomicView_mode;
            headerBar.showPeriodicViewMode(false);
//            headerBar.showAtomicViewMode(true);
            stack.getStack().visible_child_name = elements.PROPERTIES_VIEW_ID;
*/
        }
    }

